import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
import "./globals.css";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-white">
      
        <header className="flex flex-col sm:flex-row justify-between items-center px-6 sm:px-20 py-6 sm:py-9 bg-white">
          <img src="/TAPMI-Logo-1.png" alt="TAPMI Logo" className="h-16 sm:h-18 mb-4 sm:mb-0" />
          
          <div className="flex gap-4 items-center">
            <img src="/prme.jpg" alt="PRME" className="w-16 h-10 sm:w-18 sm:h-11" />
            <img src="/aacsb-logo-png_seeklogo-331672.png" alt="AACSB" className="h-10 sm:h-11" />
          </div>
        </header>


        
        <main>{children}</main>

        <footer className="bg-gray-100 p-4  flex flex-col items-center font-sans">
          <p className="text-gray-400 text-xs mb-25">© 2024 MAHE BLRU </p>
        </footer>
      </body>
    </html>
  );
}
